### ISSUE TITLE
ShareKore.h missing in xcode

### ISSUE THREAD

**Issue by matthewswallace** [luboslenco/share_kha#1]
I tried using this in a hello world example to see if I could get a better understanding of how native extensions work in Kha but I'm getting an error from xcode saying that ShareKore.h is missing.

I have my example code posted here. https://github.com/matthewswallace/HelloKha

**Comment by luboslenco** [comment]
Hi,

My guess is that the sources here may be outdated. Not much time left right now but I can get to it next week. Sorry for trouble!

For library that works with latest Kha see:
https://github.com/armory3d/haxebullet

First thing that should be handled is korefile.js update.

**Comment by matthewswallace** [comment]
No problem ... I'm trying to use your example to understand how to get my own native extension working :)
